### PR TITLE
move byline up and remove now-redundant title

### PR DESCRIPTION
**Pull request by caseywatts**
## Before, byline at bottom
screen shot 2015-02-03 at 2 37 59 pm
.
.
.
screen shot 2015-02-03 at 2 38 04 pm

## After, byline at top
screen shot 2015-02-03 at 3 00 33 pm
.
.
.
screen shot 2015-02-03 at 3 00 29 pm

### CODE REVIEW

**Comment by benjaminoakes** [comment]
:+1:

**Comment by danbernier** [comment]
- [x] Casey productive day 2
- [x] pull request
- [x] ...with PICTURES
- [x] good aesthetic sense

:saxophone:

On Tue, Feb 3, 2015 at 3:10 PM, Ben Oakes <notifications@github.com> wrote:

> Merged #2
> <https://github.com/ContinuityControl/continuitycontrol.github.io/pull/2>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ContinuityControl/continuitycontrol.github.io/pull/2#event-229534386>
> .
>

-- 


-- 

------------------------------
This email and all files transmitted with it are intended solely for use by 
the intended recipient.  Any other use is prohibited.  If you received this 
email in error, please notify the sender, delete the email and destroy all 
attachments.  Opinions and ideas expressed herein are solely those of the 
sender, and may not reflect the official position of Continuity Control.

**Comment by caseywatts** [comment]
- [x] Wikipedia agrees too - bylines belong at top not bottom. Ref: http://en.wikipedia.org/wiki/Byline

^_~

**Comment by treznick** [comment]
:trollface:?

On Tue, Feb 3, 2015 at 3:51 PM, Casey Watts <notifications@github.com>
wrote:

>
>    -  Wikipedia agrees too - bylines belong at top not bottom. Ref:
>    http://en.wikipedia.org/wiki/Byline
>
> ^_~
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ContinuityControl/continuitycontrol.github.io/pull/2#issuecomment-72732092>
> .
>



-- 
Tom Reznick
Junior Software Engineer, Continuity
914-519-8966

-- 


-- 

------------------------------
This email and all files transmitted with it are intended solely for use by 
the intended recipient.  Any other use is prohibited.  If you received this 
email in error, please notify the sender, delete the email and destroy all 
attachments.  Opinions and ideas expressed herein are solely those of the 
sender, and may not reflect the official position of Continuity Control.

**Pull request merged**
